### ISSUE TITLE
What is the correct way to use query params?

### ISSUE THREAD

**Issue by RustyDev** [gvergnaud/nextjs-dynamic-routes#2]
Thank you for the library. I'm trying to add an optional query param to handle pagination:

```/search/keywords/foo?page=2```

and my route looks like this:

```router.add({ name: 'search-keywords', pattern: '/search/keywords/:keywords'})```

**Comment by gvergnaud** [comment]
Hello, thanks for your support. Currently there is no special way of doing so. The only way of adding query params is to use the standard `href` and `as` api from [`next/link`](https://github.com/zeit/next.js/#with-link). 
Supporting standard query params is a useful feature though, I might add it in the future

**Comment by lydell** [comment]
This was added in 2.2.0! :tada: See #5.
