### ISSUE TITLE
Route doesn't work when page is index

### ISSUE THREAD

**Issue by ntgussoni** [gvergnaud/nextjs-dynamic-routes#21]
Hi! I've faced this issue a couple of times, 

`  .add({ name: "admin_index", pattern: "/admin", page: "/admin/index" })
`

That page doesn't work since it points to an index file.
Changing the file name to a different thing solves the issue

**Comment by gvergnaud** [comment]
Thanks for reporting, I'll have a look

**Comment by ntgussoni** [comment]
@gvergnaud  I tried replicating this in the example app in this repo and I couldn't. Im gonna try to find what the difference is in my app
