### ISSUE TITLE
Missing router events

### ISSUE THREAD

**Issue by tychovbh** [gvergnaud/nextjs-dynamic-routes#7]
It would be nice to be able to use router events like in nextjs.

see:
https://github.com/zeit/next.js/#router-events

so in this repo something like this:
```
import Router from ../routes'

const handleRouteChange = url => {
  console.log('App is changing to: ', url)
}

Router.events.on('routeChangeStart', handleRouteChange)
```

**Comment by tychovbh** [comment]
@gvergnaud Since I really need this now I created a pull request:
https://github.com/gvergnaud/nextjs-dynamic-routes/pull/8

I hope you can take a look at it.

**Comment by gvergnaud** [comment]
Thank you! for contributing! taking a look now
