### ISSUE TITLE
Question: Serverless NextJS ?

### ISSUE THREAD

**Issue by revskill10** [gvergnaud/nextjs-dynamic-routes#9]
I'm sorry if this isn't related to an issue. It's one question about serverless environment.
How to use this library on serverless with interface:
```js
function handler = async (req, res) => {
...
}
```
?

**Comment by gvergnaud** [comment]
You can probably use the same approach as what you can see here  https://github.com/gvergnaud/nextjs-dynamic-routes/blob/master/example/express/server.js

Your handler would be the function returned by `Router.getRequestHandler(app)`.

**Comment by lishine** [comment]
I intend to use next.js with now v2.
How to do it ?
@gvergnaud I suppose that need to use the router as is but without custom server. Write the routes in now.json ?
@revskill10 As I understand from your question, you deploy custom server with next/node ? Is it working that way? I thought custom server not working with now v2...
